### ISSUE TITLE
Backlog item: CI tasks

### ISSUE THREAD

**Issue by callmestu** [SeisoLLC/release_monitor#13]
# Summary of the issue
No github actions CD/CI tasks exist yet.  This is a major enough change that building CI along with this initial commit would be double the effort. 

## Expected behavior
We need to provide a goat CI action minimally. 

## Steps to reproduce
N/A

## Your environment
N/A

## Logs and error messages
N/A

**Comment by JonZeolla** [comment]
Will be handled in the new release hound project
